import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is auto-generated from the docs/ folder structure so it always
 * mirrors Section 4.2's repository layout — no manual sidebar maintenance as
 * new chapters land. Each phase folder carries a _category_.json (label,
 * position, and — for Phase 13 — a "Advanced Track" badge via customProps)
 * so ordering and labeling stay declarative and version-controlled.
 */
const sidebars: SidebarsConfig = {
  phaseSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
